//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public string passangerName { get; set; }
        public int transportId { get; set; }
        public int seatId { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public int ticketStateId { get; set; }
    
        public virtual Seats Seats { get; set; }
        public virtual TicketState TicketState { get; set; }
        public virtual Transports Transports { get; set; }
    }
}
