//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRoutes
    {
        public tRoutes()
        {
            this.Transports = new HashSet<Transports>();
        }
    
        public int id { get; set; }
        public int fromId { get; set; }
        public int toId { get; set; }
        public Nullable<System.DateTime> arrival { get; set; }
        public Nullable<System.DateTime> departure { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Cities Cities1 { get; set; }
        public virtual ICollection<Transports> Transports { get; set; }
    }
}
