//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatState
    {
        public SeatState()
        {
            this.Seats = new HashSet<Seats>();
        }
    
        public int id { get; set; }
        public string stateName { get; set; }
    
        public virtual ICollection<Seats> Seats { get; set; }
    }
}
