//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transports
    {
        public Transports()
        {
            this.Seats = new HashSet<Seats>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }
        public int transportTypeId { get; set; }
        public int number { get; set; }
        public int routeId { get; set; }
        public Nullable<int> seatsCount { get; set; }
        public Nullable<int> carriageNumber { get; set; }
        public Nullable<int> cost { get; set; }
    
        public virtual ICollection<Seats> Seats { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual TransportType TransportType { get; set; }
        public virtual tRoutes tRoutes { get; set; }
    }
}
